In [2]:
import torch
torch.__version__

'2.4.1+cpu'

`torch.Tensor` is PyTorch's main data structure for numerical computations.

It represents a multi-dimensional array (similar to NumPy arrays), and is the basic building block for all operations the basic building block for all operations in PyTorch.

Tensors store and operate on numerical data.

It can seamlessly run on both CPUs and GPUs

In [12]:
# Scalar
scalar = torch.tensor(3)
print(scalar)

print(scalar.ndim)

# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

tensor(3)
0


3

In [9]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)


tensor([7, 7])
1
torch.Size([2])


In [11]:
#matrix

matrix = torch.tensor([[7, 8], 
                       [9, 10]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [17]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [15]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


In [19]:
# In the tensor with 2 blocks (2, 3, 3), you have 2 layers (or blocks), and each layer has 3 rows and 3 columns.
TENSOR_2_BLOCKS = torch.tensor([[[1, 2, 3],
                                 [3, 6, 9],
                                 [2, 4, 5]],
                               
                                [[7, 8, 9],
                                 [4, 2, 1],
                                 [0, 3, 6]]])

TENSOR_2_BLOCKS.shape

torch.Size([2, 3, 3])

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7795, 0.4307, 0.8854, 0.1587],
         [0.4132, 0.1441, 0.5037, 0.0884],
         [0.5474, 0.7252, 0.9960, 0.9413]]),
 torch.float32)

In [22]:
random_tensor = torch.rand(size=(3,3,4))
random_tensor, random_tensor.dtype

(tensor([[[0.8761, 0.7252, 0.2542, 0.9455],
          [0.3950, 0.0696, 0.5708, 0.7618],
          [0.6129, 0.2280, 0.5504, 0.9211]],
 
         [[0.3241, 0.3455, 0.8487, 0.5120],
          [0.1980, 0.9256, 0.1883, 0.3846],
          [0.0709, 0.5534, 0.1068, 0.4564]],
 
         [[0.3827, 0.9254, 0.4141, 0.0496],
          [0.7526, 0.7036, 0.7747, 0.6082],
          [0.3656, 0.4213, 0.0510, 0.4785]]]),
 torch.float32)

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [1]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

NameError: name 'torch' is not defined

Automatic Differentiation: PyTorch tensors can track gradients, which is essential for training neural networks. By setting requires_grad=True, PyTorch will automatically calculate derivatives (gradients) for tensor operations, which is used for backpropagation in training.

In [8]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()

out.backward()

x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

    If you're using CUDA (like with an NVIDIA GPU), you can move a tensor to the GPU to perform computations much faster.

In [24]:
tensor_cpu = torch.Tensor([1.0, 2.0, 3.0])  # on CPU
# tensor_gpu = tensor_cpu.to('cuda')           # move to GPU (if available)

In [2]:
import torch

one_d_t =  torch.LongTensor([0,1,2])
print(one_d_t)
print(one_d_t.size())
print(one_d_t.dim())

tensor([0, 1, 2])
torch.Size([3])
1


The unsqueeze operation in PyTorch is used to add a dimension to a tensor at a specified location

if you have a batch of images represented as a tensor of shape (batch_size, height, width, channels), you might use unsqueeze to add a batch dimension at the beginning, resulting in a tensor of shape (batch_size, 1, height, width, channels).

In [4]:
two_d_t = one_d_t.unsqueeze(0)
print(two_d_t.size())
print(two_d_t.dim())
two_d_t

torch.Size([1, 3])
2


tensor([[0, 1, 2]])

In [6]:
original_tensor = torch.tensor([1, 2, 3])

# Unsqueeze operation to add a dimension at the specified location (index 1 in this case)
unsqueezed_tensor = original_tensor.unsqueeze(1)

# Print the original and unsqueezed tensors
print("Original Tensor:", original_tensor, original_tensor.shape, original_tensor.dim())
print("Unsqueezed Tensor:", unsqueezed_tensor, unsqueezed_tensor.shape, unsqueezed_tensor.dim() )

Original Tensor: tensor([1, 2, 3]) torch.Size([3]) 1
Unsqueezed Tensor: tensor([[1],
        [2],
        [3]]) torch.Size([3, 1]) 2


In [14]:
import torch

# Original matrix
original_matrix = torch.tensor([[1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 9]])

# Transpose using torch.transpose
transposed_matrix = torch.transpose(original_matrix, 0, 1)

# Transpose using .t() method
t_method_transposed_matrix = original_matrix.t()

# Print the original and transposed matrices
print("Original Matrix:")
print(original_matrix)
print("\nTransposed Matrix (torch.transpose):")
print(transposed_matrix)
print("\nTransposed Matrix (.t() method):")
print(t_method_transposed_matrix)

Original Matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Transposed Matrix (torch.transpose):
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

Transposed Matrix (.t() method):
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
