In [3]:
import torch

one_d_t =  torch.LongTensor([0,1,2])
print(one_d_t)
print(one_d_t.size())
print(one_d_t.dim())

tensor([0, 1, 2])
torch.Size([3])
1


The unsqueeze operation in PyTorch is used to add a dimension to a tensor at a specified location

if you have a batch of images represented as a tensor of shape (batch_size, height, width, channels), you might use unsqueeze to add a batch dimension at the beginning, resulting in a tensor of shape (batch_size, 1, height, width, channels).

In [4]:
two_d_t = one_d_t.unsqueeze(0)
print(two_d_t.size())
print(two_d_t.dim())
two_d_t

torch.Size([1, 3])
2


tensor([[0, 1, 2]])

In [6]:
original_tensor = torch.tensor([1, 2, 3])

# Unsqueeze operation to add a dimension at the specified location (index 1 in this case)
unsqueezed_tensor = original_tensor.unsqueeze(1)

# Print the original and unsqueezed tensors
print("Original Tensor:", original_tensor, original_tensor.shape, original_tensor.dim())
print("Unsqueezed Tensor:", unsqueezed_tensor, unsqueezed_tensor.shape, unsqueezed_tensor.dim() )

Original Tensor: tensor([1, 2, 3]) torch.Size([3]) 1
Unsqueezed Tensor: tensor([[1],
        [2],
        [3]]) torch.Size([3, 1]) 2


In [14]:
import torch

# Original matrix
original_matrix = torch.tensor([[1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 9]])

# Transpose using torch.transpose
transposed_matrix = torch.transpose(original_matrix, 0, 1)

# Transpose using .t() method
t_method_transposed_matrix = original_matrix.t()

# Print the original and transposed matrices
print("Original Matrix:")
print(original_matrix)
print("\nTransposed Matrix (torch.transpose):")
print(transposed_matrix)
print("\nTransposed Matrix (.t() method):")
print(t_method_transposed_matrix)

Original Matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Transposed Matrix (torch.transpose):
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

Transposed Matrix (.t() method):
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])
