In [4]:
import torch
from torch.utils.data import Dataset, DataLoader

import torch.nn as nn

In [5]:
size = (2, 3)
x = torch.randn(*size)  # Creates a tensor with normally distributed random values (mean=0, std=1)
print(x)

tensor([[ 0.2809,  0.2855,  0.1491],
        [ 1.6699, -0.0231,  0.1176]])


In [6]:
x_ones = torch.ones(*size)   # Tensor filled with ones
x_zeros = torch.zeros(*size) # Tensor filled with zeros
print("Ones tensor:", x_ones)
print("Zeros tensor:", x_zeros)

Ones tensor: tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
L = [[1, 2, 3], [4, 5, 6]]
x = torch.tensor(L)  # Converts a nested list to a tensor
print(x)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [8]:
y = x.clone()  # Creates a clone of tensor x
x[0, 0] = 999  # Modify x to show that y is unaffected
print("Original x:", x)
print("Cloned y:", y)

Original x: tensor([[999,   2,   3],
        [  4,   5,   6]])
Cloned y: tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
x = torch.randn(3, 3, requires_grad=True)
print(x)
print("Before no_grad block, requires_grad:", x.requires_grad)

with torch.no_grad():
    x = x * 2
    print("Inside no_grad block, requires_grad:", x.requires_grad)

print(x)
print("After no_grad block, requires_grad:", x.requires_grad)

tensor([[-0.8734,  0.0622, -1.0020],
        [ 0.1589, -1.3428,  0.3411],
        [ 0.7378,  3.3918, -0.3597]], requires_grad=True)
Before no_grad block, requires_grad: True
Inside no_grad block, requires_grad: False
tensor([[-1.7468,  0.1244, -2.0041],
        [ 0.3179, -2.6857,  0.6823],
        [ 1.4756,  6.7835, -0.7195]])
After no_grad block, requires_grad: False


In [11]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)  # Track computation history
y = x ** 2  # y = [1, 4, 9]
z = y.sum()  # z = 1 + 4 + 9 = 14

# Compute gradients
z.backward()  # Computes dz/dx
print("Gradients of x:", x.grad)

Gradients of x: tensor([2., 4., 6.])


In [12]:
x = torch.randn(2, 3, 4)  # A tensor with shape (2, 3, 4)
print(x.size())           # Returns the shape of the tensor

torch.Size([2, 3, 4])
