In [1]:
import torch
torch.__version__

'2.4.1+cpu'

`torch.Tensor` is PyTorch's main data structure for numerical computations.

It represents a multi-dimensional array (similar to NumPy arrays), and is the basic building block for all operations the basic building block for all operations in PyTorch.

Tensors store and operate on numerical data.

It can seamlessly run on both CPUs and GPUs

In [12]:
# Scalar
scalar = torch.tensor(3)
print(scalar)

print(scalar.ndim)

# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

tensor(3)
0


3

In [9]:
# Vector
vector = torch.tensor([7, 7])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 7])
1
torch.Size([2])


In [11]:
#matrix

matrix = torch.tensor([[7, 8], 
                       [9, 10]])

print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [17]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])


In [15]:
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


In [19]:
# In the tensor with 2 blocks (2, 3, 3), you have 2 layers (or blocks), and each layer has 3 rows and 3 columns.
TENSOR_2_BLOCKS = torch.tensor([[[1, 2, 3],
                                 [3, 6, 9],
                                 [2, 4, 5]],
                               
                                [[7, 8, 9],
                                 [4, 2, 1],
                                 [0, 3, 6]]])

TENSOR_2_BLOCKS.shape

torch.Size([2, 3, 3])

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7795, 0.4307, 0.8854, 0.1587],
         [0.4132, 0.1441, 0.5037, 0.0884],
         [0.5474, 0.7252, 0.9960, 0.9413]]),
 torch.float32)

In [22]:
random_tensor = torch.rand(size=(3,3,4))
random_tensor, random_tensor.dtype

(tensor([[[0.8761, 0.7252, 0.2542, 0.9455],
          [0.3950, 0.0696, 0.5708, 0.7618],
          [0.6129, 0.2280, 0.5504, 0.9211]],
 
         [[0.3241, 0.3455, 0.8487, 0.5120],
          [0.1980, 0.9256, 0.1883, 0.3846],
          [0.0709, 0.5534, 0.1068, 0.4564]],
 
         [[0.3827, 0.9254, 0.4141, 0.0496],
          [0.7526, 0.7036, 0.7747, 0.6082],
          [0.3656, 0.4213, 0.0510, 0.4785]]]),
 torch.float32)

In [21]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [3]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=3)
zero_to_ten

tensor([0, 3, 6, 9])

In [6]:
float_default_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_default_tensor.shape, float_default_tensor.dtype, float_default_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [7]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

(torch.float16, tensor([3., 6., 9.], dtype=torch.float16))

Automatic Differentiation: PyTorch tensors can track gradients, which is essential for training neural networks. By setting requires_grad=True, PyTorch will automatically calculate derivatives (gradients) for tensor operations, which is used for backpropagation in training.

In [8]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
out = x.pow(2).sum()

out.backward()

x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

    If you're using CUDA (like with an NVIDIA GPU), you can move a tensor to the GPU to perform computations much faster.

In [19]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [20]:
# Count number of devices
torch.cuda.device_count()

0

In [24]:
tensor_cpu = torch.Tensor([1.0, 2.0, 3.0])  # on CPU
# tensor_gpu = tensor_cpu.to('cuda')           # move to GPU (if available)

In [22]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [23]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device) # Putting a tensor on GPU using to(device) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [24]:
# Moving tensors back to the CPU

# NumPy does not leverage the GPU

# If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_gpu.numpy()

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy() # This returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.
tensor_back_on_cpu

array([1, 2, 3])

In [20]:
# Multiplication 

# Element wise multiplication

tensor = torch.tensor([1, 2, 3])

print("Equals:", tensor * tensor)

# Matrix Multiplication / Dot Product

print(torch.matmul(tensor, tensor))
print(tensor @ tensor)

Equals: tensor([1, 4, 9])
tensor(14)
tensor(14)


In [21]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 1.3 ms


tensor(14)

In [22]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [35]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

# Transpose

print(tensor_B.T, tensor_B.T.shape)

# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)


tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]]) torch.Size([2, 3])


tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [71]:
import torch

# Original matrix
original_matrix = torch.tensor([[1, 2, 3],
                                [4, 5, 6],
                                [7, 8, 9]])

# Transpose using torch.transpose
transposed_matrix = torch.transpose(original_matrix, 0, 1)

# Transpose using .t() method
t_method_transposed_matrix = original_matrix.t()

# Print the original and transposed matrices
print("Original Matrix:")
print(original_matrix)
print("\nTransposed Matrix (torch.transpose):")
print(transposed_matrix)
print("\nTransposed Matrix (.t() method):")
print(t_method_transposed_matrix)

Original Matrix:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Transposed Matrix (torch.transpose):
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

Transposed Matrix (.t() method):
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [47]:
#change the datatypes of tensors

# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
print(tensor_float16.dtype)

torch.float32
torch.float16


In [44]:
# Create a tensor
x = torch.arange(0, 100, 10)

print(x)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
Index where max value occurs: 2
Index where min value occurs: 0


In [55]:
x = torch.randn(4, 4)
print(x)

# Returns a new tensor with the same data as the self tensor but of a different shape
y = x.view(8,2)
y

tensor([[-0.3609, -0.0606,  0.0733,  0.8187],
        [ 1.4805,  0.3449, -1.4241, -0.1163],
        [ 0.2176, -0.0467, -1.4335, -0.5665],
        [-0.4253,  0.2625, -1.4391,  0.5214]])


tensor([[-0.3609, -0.0606],
        [ 0.0733,  0.8187],
        [ 1.4805,  0.3449],
        [-1.4241, -0.1163],
        [ 0.2176, -0.0467],
        [-1.4335, -0.5665],
        [-0.4253,  0.2625],
        [-1.4391,  0.5214]])

In [58]:
x = torch.arange(1., 8.)
print(x, x.shape)

# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

tensor([1., 2., 3., 4., 5., 6., 7.]) torch.Size([7])


(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [62]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)

x_stacked = torch.stack([x, x, x, x], dim=1)
print(x_stacked)

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])


In [63]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [67]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])


The unsqueeze operation in PyTorch is used to add a dimension to a tensor at a specified location

if you have a batch of images represented as a tensor of shape (batch_size, height, width, channels), you might use unsqueeze to add a batch dimension at the beginning, resulting in a tensor of shape (batch_size, 1, height, width, channels).

In [70]:
original_tensor = torch.tensor([1, 2, 3])

# Unsqueeze operation to add a dimension at the specified location (index 1 in this case)
unsqueezed_tensor = original_tensor.unsqueeze(1)

# Print the original and unsqueezed tensors
print("Original Tensor:", original_tensor, original_tensor.shape, original_tensor.dim())
print("Unsqueezed Tensor:", unsqueezed_tensor, unsqueezed_tensor.shape, unsqueezed_tensor.dim() )

Original Tensor: tensor([1, 2, 3]) torch.Size([3]) 1
Unsqueezed Tensor: tensor([[1],
        [2],
        [3]]) torch.Size([3, 1]) 2


In [9]:
# NumPy array to tensor
import torch
import numpy as np  
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor it'll keep the same datatype
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [10]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [16]:
# Reproducibility

import torch
import random

# # Set the random seed
RANDOM_SEED=42
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) 
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])